### ISSUE TITLE
format for contact info

### ISSUE THREAD

**Issue by NickleDave** [Atlanta-BEST-Data-Science/BEST-contacts#1]
@lahoffm was thinking it should be something like

Name:
Degree program (current for undergraduates/graduates, field of your Ph.D. for post-docs):
Research group you work with:
Programming languages and software libraries you use:

**Comment by NickleDave** [comment]
oh and maybe
Github:
website:
twitter:

**Comment by lahoffm** [comment]
Sure. Could it just be in a markdown file in a simple table?

**Comment by NickleDave** [comment]
yes.
Not sure if this is what you were suggesting but why not just have each person submit a PR with a separate FirstnameLastname.md file inside of a ./contacts subfolder that the repo will have. I'll submit my own PR so you can see what I mean.

**Comment by NickleDave** [comment]
We could then have a script that assimilates all the separate FirstnameLastname.md files into one "contacts.md" file. That way we avoid dealing with 3000 merge conflicts

**Comment by lahoffm** [comment]
Issue can be closed now?

**Comment by NickleDave** [comment]
Sure

**Comment by NickleDave** [comment]
Hey BEST Data Scientists,

Happy New Year.

Just sharing some workshops that ECDS and QTM are offering this semester
(below).
If you are thinking about ways to present your data science projects, e.g.
to potential employers, I'd recommend the Publishing with Github Pages
workshop.
Github provides you a relatively painless way to publish documentation for
your projects and a personal blog.

--David

---------- Forwarded message ----------
From: Owens, Debora <debora.owens@emory.edu>
Date: Fri, Jan 12, 2018 at 3:11 PM
Subject: Upcoming Workshops - Mark your calendars!
To: QTMEVENTS@listserv.cc.emory.edu


<http://tinyurl.com/ecds-spring-2018>



Debora T. Owens

The Institute for Quantitative Theory & Methods
<http://quantitative.emory.edu/>

Modern Languages Building, 408C

Emory University

(404) 727-0538

*Connect with us
<http://quantitative.emory.edu/for-industry/industry-engagement.html>:
 Twitter <https://twitter.com/?lang=en>, Facebook,
<https://www.facebook.com/TheInstituteForQuantitativeTheoryAndMethods/>*

*Quantitative Sciences @ Emory YouTube <https://youtu.be/VX0czO0YGF4> *







-- 
David Nicholson, Ph.D.
nickledave.github.io
https://github.com/NickleDave
Sober Lab <http://www.biology.emory.edu/research/Sober/Home.html>
